# Generated by Django 4.1.7 on 2023-03-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='date_entered_status',
            field=models.DateTimeField(null=True, verbose_name='Дата входа заявки в статус'),
        ),
    ]
