# Generated by Django 4.1.7 on 2023-03-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_requests', '0002_alter_connectionrequest_date_entered_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='comment_TVP_ShPD',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий ТВП ШПД'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='date_entered_status',
            field=models.DateTimeField(verbose_name='Дата входа заявки в статус'),
        ),
    ]
