# Generated by Django 4.1.7 on 2023-03-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_requests', '0003_alter_connectionrequest_comment_tvp_shpd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='id_agreement_KURS',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ID Договор КУРС'),
        ),
    ]
