# Generated by Django 4.1.7 on 2023-03-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_requests', '0004_alter_connectionrequest_id_agreement_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Примечание'),
        ),
    ]
