# Generated by Django 4.1.7 on 2023-03-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_requests', '0005_alter_connectionrequest_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='contact_phone_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='contract_created_by_fio',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО сотрудника создавшего договор'),
        ),
    ]
