# Generated by Django 4.1.7 on 2023-03-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_requests', '0006_alter_connectionrequest_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='APTV_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность этапа АПТВ'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='DO_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность этапа ДО'),
        ),
    ]
