# Generated by Django 4.1.7 on 2023-03-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_requests', '0007_alter_connectionrequest_aptv_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionrequest',
            options={'ordering': ('-date_entered_status',), 'verbose_name': 'Заявка на подключение', 'verbose_name_plural': 'Заявки на подключение'},
        ),
        migrations.AlterField(
            model_name='client',
            name='INN',
            field=models.PositiveBigIntegerField(db_index=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='number',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='tvppresence',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tvptesttype',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
